version: '3.7'
services:
#  kafka-to-elastic-service:
#    image: ${GROUP_ID}/kafka-to-elastic-service:${SERVICE_VERSION:-latest}
#    container_name: kafka2elastic
#    depends_on:
#      - config-server
#      - twitter-to-kafka-service
#      - kafka-broker-1
#      - kafka-broker-2
#      - kafka-broker-3
#      - elastic-1
#      - elastic-2
#      - elastic-3
#    ports:
#      - "5007:5007"
#    volumes:
#      - "./docker-logs:/workspace/kafka-to-elastic-service/logs"
#      - "./check-kafka-topics-created.sh:/usr/local/bin/check-kafka-topics-created.sh"
#    user: root
#    entrypoint: [ "check-kafka-topics-created.sh" ]
#    environment:
#      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -Xms128m -Xmx256m"
#      - "KAFKA-CONFIG_TOPIC-NAME=twitter-topic"
#      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
#      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
#      - "JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}"
#      - "TWITTER-TO-KAFKA-SERVICE_ENABLE-MOCK-TWEETS=false"
#      - "SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888"
#      - "SPRING_CLOUD_CONFIG_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}"
#      - "ELASTIC-CONFIG_INDEX-NAME=twitter-index"
#      - "ELASTIC-CONFIG_CONNECTION-URL=http://elastic-1:9200"
#    networks:
#      - ${GLOBAL_NETWORK:-services}
  twitter-to-kafka-service:
    image: ${GROUP_ID}/twitter-to-kafka-service:${SERVICE_VERSION:-latest}
    container_name: twitter2kafka
    depends_on:
      - zookeeper
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - schema-registry
      - config-server
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/twitter-to-kafka-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "KAFKA-CONFIG_TOPIC-NAME=twitter-topic"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}"
      - "TWITTER-TO-KAFKA-SERVICE_ENABLE-MOCK-TWEETS=false"
      - "SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888"
      - "SPRING_CLOUD_CONFIG_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}"
    networks:
      - ${GLOBAL_NETWORK:-services}
  config-server:
    image: ${GROUP_ID}/config-server:${SERVICE_VERSION:-latest}
    ports:
      - "5006:5006"
      - "8888:8888"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      - "JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}"
      - "SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}"
    networks:
      - ${GLOBAL_NETWORK:-services}
#  elastic-query-service:
#    image: ${GROUP_ID}/elastic-query-service:${SERVICE_VERSION:-latest}
#    ports:
#      - "5008:5008"
#      - "8183:8183"
#    volumes:
#      - "./docker-logs:/workspace/elastic-query-service/logs"
#      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
#    entrypoint: [ "check-config-server-started.sh" ]
#    depends_on:
#      - config-server
#      - kafka-to-elastic-service
#      - elastic-1
#      - elastic-2
#      - elastic-3
#    environment:
#      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
#      - "SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}"
#      - "ELASTIC-CONFIG_INDEX-NAME=twitter-index"
#      - "ELASTIC-CONFIG_CONNECTION-URL=http://elastic-1:9200"
#      - "SERVER_PORT=8183"
#      - "SERVER_SERVLET_CONTEXT-PATH=/elastic-query-service"
#      - "SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888"
#      - "SPRING_CLOUD_CONFIG_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}"
#      - "JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}"
#    networks:
#      - ${GLOBAL_NETWORK:-services}