server:
  port: 8080
spring:
  application:
    name: twitter-to-kafka-service
twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch