server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/augustas3000/edmc-spring-cloud-config-server-repo.git
          username: augustas3000
          password: ENC(8VgEYn2UlqDFoCFfiMOL0DnQfDoyGsR1AnBQjpMX2wxwqFQahP3IBWsjhhfYqo86xUfc7NnB/7Z1pV23iEky/6+bupG/yVvVfXcKTHBEvYA=)
          clone-on-start: true
          default-label: main
      fail-fast: true
  security:
    user:
      name: nunudv
logging:
  level:
    org.eclipse.jgit: DEBUG
    org.springframework.cloud: DEBUG