server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/augustas3000/edmc-spring-cloud-config-server-repo
          username: ENC(dSqOz4R8brb7LTAZcJ+PT339iswy2wPqPiBMcvEoEHKwYM8Sea9sraNZUdfb7fxJ)
          password: ENC(WXOS3tvqrefhCghB8vjS+AWcFPdBE0yyGlwudlkNvVt339m7sCM2I8EKogsc6nYkgwgTxYDfdenx3oLSZDPZBwaVG3PcH0xu2mygefzLJp0=)
          clone-on-start: true
      fail-fast: true
  security:
    user:
      name: ENC(xMqeA7D0T9/+7iq4V1LfbMDdqHStlvtGxRQwGFg0EZCLXwe030p7WZKOebdrI7UPYNuUujAIHvuucx/3w5aSTw==)
      password: ENC(aBOpgMv+RmdUkT54KpAKkNGvF9T/xb/DEdNb1pJtcEUO+UCbY31WMmiLDW79XWVcTbAzKg+D+WfkISCHEvcZmw==)
